function stat(id, name, description) {
  return { id, name, description };
}

function entry(id, name, description = '') {
  return { id, name, description };
}

function resource(id, name, max) {
  return { id, name, max };
}

export const DEFAULT_TEMPLATES = [
  {
    id: 'builtin-sessizlik',
    label: '⭐ Sessizlik',
    name: 'Sessizlik',
    theme: 'post-apocalyptic',
    stats: [
      stat('guc', 'Güç', 'Ham fiziksel kuvvet, yakın dövüş, kaldırma/kırma'),
      stat('dayaniklilik', 'Dayanıklılık', 'Acıya, yorgunluğa, zehre direnç'),
      stat('ceviklik', 'Çeviklik', 'Refleks, denge, gizlenme, kaçış'),
      stat('zeka', 'Zeka', 'Analiz, bilgi, teknik/tamirat, bulmaca çözme'),
      stat('algi', 'Algı', 'Fark etme, iz sürme, tehlikeyi sezme'),
      stat('karizma', 'Karizma', 'İkna, liderlik, pazarlık'),
      stat('empati', 'Empati', 'İnsanları okuma, güven kurma, teselli etme'),
    ],
    resources: [resource('saglik', 'Sağlık', 5)],
    races: [],
    classes: [],
    subclasses: [
      entry('siyirici', 'Sıyırıcı', 'Eski dünya kalıntılarını arayan biri. İlişkili traitler: Eski Dünya Gözü ya da Tuzak Ustası (birini seç).'),
      entry('izci', 'İzci', 'Vahşi doğada yol bulan, avlanan biri. İlişkili traitler: İz Sürücü ya da Gölge Gibi (birini seç).'),
      entry('sifaci', 'Şifacı', 'Şifa bilgisi edinmiş biri. İlişkili traitler: Bitki Bilgisi ya da Sakin Ses (birini seç).'),
      entry('eski-dunya-bilgini', 'Eski Dünya Bilgini', 'Eski kayıtlara ilgi duyan biri. İlişkili traitler: Yazıyı Çözer ya da Mekanik Sezgisi (birini seç).'),
    ],
    traits: [
      entry('eski-dunya-gozu', 'Eski Dünya Gözü', 'Eski teknoloji/eşyaları tanıma. (Sıyırıcı dalı)'),
      entry('tuzak-ustasi', 'Tuzak Ustası', 'Tuzak kurma/sezme. (Sıyırıcı dalı)'),
      entry('iz-surucu', 'İz Sürücü', 'Takip etme, yön bulma. (İzci dalı)'),
      entry('golge-gibi', 'Gölge Gibi', 'Doğada fark edilmeden hareket etme. (İzci dalı)'),
      entry('bitki-bilgisi', 'Bitki Bilgisi', 'Şifalı/zehirli bitkileri tanıma, ilk yardım. (Şifacı dalı)'),
      entry('sakin-ses', 'Sakin Ses', 'Paniklemiş/yaralı birini yatıştırma. (Şifacı dalı)'),
      entry('yaziyi-cozer', 'Yazıyı Çözer', 'Eski dilleri/kayıtları okuma. (Eski Dünya Bilgini dalı)'),
      entry('mekanik-sezgisi', 'Mekanik Sezgisi', 'Karmaşık eski makineleri anlama. (Eski Dünya Bilgini dalı)'),
    ],
    perks: [
      entry('keskin-nisanci', 'Keskin Nişancı', 'Uzun menzilli saldırılarda avantaj sağlar.'),
      entry('hayatta-kalma-icgudusu', 'Hayatta Kalma İçgüdüsü', 'Doğada yiyecek/su bulmada avantaj sağlar.'),
      entry('sogukkanli', 'Soğukkanlı', 'Panik/korku anlarında avantaj sağlar.'),
      entry('supheci-goz', 'Şüpheci Göz', 'Yalan/manipülasyonu fark etmede avantaj sağlar.'),
      entry('karizmatik-anlatici', 'Karizmatik Anlatıcı', 'Toplulukla konuşurken/ikna ederken avantaj sağlar.'),
      entry('sessiz-adimlar', 'Sessiz Adımlar', 'Gizlenme/fark edilmemede avantaj sağlar.'),
      entry('demir-bunye', 'Demir Bünye', 'Zehir/hastalık/yorgunluğa karşı avantaj sağlar.'),
      entry('tamirci-eller', 'Tamirci Eller', 'Makine/silah tamiratında avantaj sağlar.'),
    ],
    items: [],
  },
  {
    id: 'builtin-dnd',
    label: '⭐ D&D Tarzı (Klasik Fantazi)',
    name: 'Klasik Fantazi Kampanyası',
    theme: 'high-fantasy',
    stats: [
      stat('guc', 'Güç', 'Yakın dövüş, kaldırma, fiziksel zorlama'),
      stat('ceviklik', 'Çeviklik', 'Refleks, denge, uzaktan saldırı'),
      stat('dayaniklilik', 'Dayanıklılık', 'Can, yorgunluğa ve hastalığa direnç'),
      stat('zeka', 'Zeka', 'Bilgi, büyü çözümleme, mantık'),
      stat('bilgelik', 'Bilgelik', 'Sezgi, algı, irade gücü'),
      stat('karizma', 'Karizma', 'İkna, liderlik, büyüsel etki'),
    ],
    resources: [resource('can', 'Can Puanı', 20)],
    races: [
      entry('insan', 'İnsan', 'Uyumlu ve hırslı, her yolda kendine yer bulur.'),
      entry('elf', 'Elf', 'Zarif ve uzun ömürlü, doğa ve büyüyle bağlantılı.'),
      entry('cuce', 'Cüce', 'Dayanıklı ve inatçı, zanaat ve savaşta usta.'),
      entry('yari-ork', 'Yarı-Ork', 'Güçlü ve azimli, iki dünya arasında sıkışmış.'),
      entry('halfling', 'Halfling', 'Küçük yapılı, şanslı ve çevik.'),
    ],
    classes: [
      entry('savasci', 'Savaşçı', 'Silah ve zırh ustası, ön safta dövüşür.'),
      entry('buyucu', 'Büyücü', 'Büyü kitabından güç çeken bilgin.'),
      entry('hirsiz', 'Hırsız', 'Gizlilik, çeviklik ve kurnazlıkla hayatta kalır.'),
      entry('rahip', 'Rahip', 'Kutsal güçlerle şifa verir ve korur.'),
      entry('ranger', 'Ranger', 'Doğa bilgisiyle donanmış avcı ve izci.'),
    ],
    subclasses: [
      entry('sampiyon', 'Şampiyon', 'Ham güce odaklanan savaşçı yolu.'),
      entry('illuzyonist', 'İllüzyonist', 'Algıyı büken büyücü okulu.'),
      entry('golge-ustasi', 'Gölge Ustası', 'Karanlıkta çalışan hırsız yolu.'),
      entry('paladin', 'Paladin', 'Yeminle bağlı kutsal savaşçı.'),
      entry('izci-yolu', 'İzci Yolu', 'Vahşi doğada ustalaşmış ranger dalı.'),
    ],
    traits: [
      entry('cesur', 'Cesur', 'Tehlike karşısında geri adım atmaz.'),
      entry('sadik', 'Sadık', 'Yoldaşlarını asla yüzüstü bırakmaz.'),
      entry('kurnaz', 'Kurnaz', 'Her durumdan bir çıkış yolu bulur.'),
      entry('merakli', 'Meraklı', 'Bilinmeyeni keşfetmeye can atar.'),
      entry('inatci', 'İnatçı', 'Fikrini kolay kolay değiştirmez.'),
    ],
    perks: [
      entry('ekstra-saldiri', 'Ekstra Saldırı', 'Bir turda birden fazla saldırı yapabilir.'),
      entry('buyu-ustaligi', 'Büyü Ustalığı', 'Büyülerini daha güçlü ve isabetli kullanır.'),
      entry('gizlenme-yetenegi', 'Gizlenme Yeteneği', 'Fark edilmeden hareket etmede üstündür.'),
      entry('sifa-dokunusu', 'Şifa Dokunuşu', 'Dokunuşuyla yaraları iyileştirir.'),
      entry('keskin-nisanci', 'Keskin Nişancı', 'Uzun menzilli atışlarda isabeti yüksektir.'),
    ],
    items: [
      entry('kisa-kilic', 'Kısa Kılıç', 'Hafif ve hızlı bir yakın dövüş silahı.'),
      entry('uzun-yay', 'Uzun Yay', 'Menzilli saldırılar için güvenilir bir silah.'),
      entry('deri-zirh', 'Deri Zırh', 'Hafif, esnekliği bozmayan bir zırh.'),
      entry('sifa-iksiri', 'Şifa İksiri', 'İçildiğinde yaraları iyileştirir.'),
      entry('mesale', 'Meşale', 'Karanlık yerleri aydınlatır.'),
    ],
  },
  {
    id: 'builtin-fate',
    label: '⭐ FATE Tarzı',
    name: 'FATE Kampanyası',
    theme: 'high-fantasy',
    stats: [
      stat('dikkatli', 'Dikkatli', 'Gözlem, hassasiyet, planlama'),
      stat('kurnaz', 'Kurnaz', 'Zeka, hile, manipülasyon'),
      stat('curetkar', 'Cüretkar', 'Cesaret, doğrudan yüzleşme'),
      stat('hizli', 'Hızlı', 'Refleks, çeviklik, tepki süresi'),
      stat('zorlu', 'Zorlu', 'Fiziksel dayanıklılık, sertlik'),
      stat('sinsi', 'Sinsi', 'Gizlilik, sabır, arka plandan hareket'),
    ],
    resources: [
      resource('fiziksel-stres', 'Fiziksel Stres', 2),
      resource('zihinsel-stres', 'Zihinsel Stres', 2),
      resource('fate-puani', 'Fate Puanı', 3),
    ],
    races: [],
    classes: [],
    subclasses: [],
    traits: [
      entry('yuksek-konsept', 'Yüksek Konsept', 'Karakteri bir cümlede özetleyen temel aspect.'),
      entry('sorun', 'Sorun', 'Karakterin başına sürekli bela açan zayıflığı.'),
      entry('ikinci-kimlik', 'İkinci Kimlik', 'Gizli ya da ikinci bir yaşamı/rolü.'),
      entry('baglanti', 'Bağlantı', 'Önemli bir kişi ya da gruba olan bağı.'),
      entry('gizli-gecmis', 'Gizli Geçmiş', 'Henüz kimsenin bilmediği bir geçmiş olay.'),
    ],
    perks: [
      entry('ekstra-beceri', 'Ekstra Beceri Kullanımı', 'Bir beceriyi normalden daha esnek kullanabilir.'),
      entry('yeniden-zar', 'Yeniden Zar Atma Hakkı', 'Belirli koşullarda bir zarı yeniden atabilir.'),
      entry('sahne-avantaji', 'Sahne Avantajı Yaratma', 'Sahneye kalıcı bir avantaj etiketi ekleyebilir.'),
      entry('ekstra-stres', 'Ekstra Stres Kutusu', 'Daha fazla stres/hasar kaldırabilir.'),
      entry('uzman-manevra', 'Uzman Manevra', 'Belirli bir alanda özel bir manevra açar.'),
    ],
    items: [
      entry('kisisel-esya', 'Kişisel Eşya', 'Karaktere özel, duygusal değeri olan bir obje.'),
      entry('aile-yadigari', 'Aile Yadigarı', 'Aileden kalma, hikayesi olan bir eşya.'),
      entry('is-aleti', 'İş Aleti', 'Karakterin mesleğiyle ilgili bir alet.'),
      entry('gizli-not', 'Gizli Not', 'Önemli bilgi içeren, gizlenmiş bir not.'),
      entry('sansli-obje', 'Şanslı Obje', 'Karakterin yanından ayırmadığı uğurlu eşya.'),
    ],
  },
  {
    id: 'builtin-cyberpunk',
    label: '⭐ Cyberpunk Görevi Tarzı',
    name: 'Cyberpunk Görevi',
    theme: 'cyberpunk',
    stats: [
      stat('beden', 'Beden', 'Fiziksel güç ve dayanıklılık'),
      stat('refleks', 'Refleks', 'Hız, çeviklik, silah kullanımı'),
      stat('teknik', 'Teknik', 'Hackleme, tamirat, mühendislik'),
      stat('zeka', 'Zeka', 'Analiz, strateji, bilgi'),
      stat('sogukkanlilik', 'Soğukkanlılık', 'Stres altında karar verme, irade'),
    ],
    resources: [
      resource('can', 'Can Puanı', 10),
      resource('isi', 'Isı', 10),
    ],
    races: [],
    classes: [
      entry('solo', 'Solo', 'Silahlı çatışma uzmanı, tek başına ya da kiralık.'),
      entry('netrunner', 'Netrunner', 'Dijital ağlarda gezinen hacker.'),
      entry('teknisyen', 'Teknisyen', 'Silah, implant ve araç ustası.'),
      entry('medic', 'Medic', 'Sokak cerrahı, hayat kurtaran uzman.'),
      entry('fixer', 'Fixer', 'Bağlantılarla iş bağlayan aracı.'),
    ],
    subclasses: [
      entry('kurumsal-ajan', 'Kurumsal Ajan', 'Bir mega-şirkete bağlı gizli operatör.'),
      entry('sokak-samuray', 'Sokak Samuray', 'Kurumlardan bağımsız, sokakta hayatta kalan savaşçı.'),
    ],
    traits: [
      entry('sadik', 'Sadık', 'Ekibini kolay terk etmez.'),
      entry('guvensiz', 'Güvensiz', 'Kimseye tam güvenmez.'),
      entry('hirsli', 'Hırslı', 'Her zaman daha fazlasını ister.'),
      entry('sogukkanli-trait', 'Soğukkanlı', 'Baskı altında bile net düşünür.'),
      entry('asi', 'Asi', 'Otoriteye karşı doğal bir direnci var.'),
    ],
    perks: [
      entry('hizli-refleks', 'Hızlı Refleks', 'Çatışmada ilk hareket eden o olur.'),
      entry('hackleme-ustaligi', 'Hackleme Ustalığı', 'Dijital sistemlere sızmada üstündür.'),
      entry('silah-ustaligi', 'Silah Ustalığı', 'Ateşli silahlarla isabeti yüksektir.'),
      entry('cazibe', 'Cazibe', 'İnsanları etkilemede doğal bir yeteneği var.'),
      entry('dayaniklilik-perk', 'Dayanıklılık', 'Ağır hasarlara karşı daha dirençli.'),
    ],
    items: [
      entry('akilli-silah', 'Akıllı Silah', 'Hedef kilitleme özellikli ateşli silah.'),
      entry('noral-implant', 'Nöral İmplant', 'Refleksleri ve zekayı artıran implant.'),
      entry('hacking-deck', 'Hacking Deck', 'Dijital sistemlere sızmak için gerekli cihaz.'),
      entry('zirhli-ceket', 'Zırhlı Ceket', 'Gündelik görünümlü, kurşun geçirmez ceket.'),
      entry('sahte-kimlik', 'Sahte Kimlik', 'Takip edilmeden dolaşmayı sağlayan sahte kimlik.'),
    ],
  },
  {
    id: 'builtin-vampire',
    label: '⭐ Vampir Klanları Tarzı',
    name: 'Vampir Klanları',
    theme: 'vampire',
    stats: [
      stat('guc', 'Güç', 'Fiziksel kuvvet ve doğaüstü dayanıklılık'),
      stat('cekicilik', 'Çekicilik', 'Karizma, ikna, sosyal manipülasyon'),
      stat('kurnazlik', 'Kurnazlık', 'Entrika, strateji, gözlem'),
      stat('irade', 'İrade', 'Açlığa ve dürtülere karşı direnç'),
      stat('disiplin', 'Disiplin', 'Doğaüstü güçleri kontrol etme becerisi'),
    ],
    resources: [
      resource('kan-puani', 'Kan Puanı', 10),
      resource('insanlik', 'İnsanlık', 10),
    ],
    races: [],
    classes: [
      entry('ventrue', 'Ventrue', 'Asil ve komuta eden, gücü elinde tutan klan.'),
      entry('toreador', 'Toreador', 'Sanata ve güzelliğe düşkün, tutkulu klan.'),
      entry('nosferatu', 'Nosferatu', 'Gölgelerde yaşayan, sırların koruyucusu klan.'),
      entry('malkavian', 'Malkavian', 'Çılgınlık ve öngörü arasında gidip gelen klan.'),
      entry('tremere', 'Tremere', 'Kan büyüsünde ustalaşmış, hiyerarşik klan.'),
    ],
    subclasses: [],
    traits: [
      entry('asil', 'Asil', 'Duruşu ve tavrıyla saygı uyandırır.'),
      entry('gizemli', 'Gizemli', 'Geçmişi hakkında az şey paylaşır.'),
      entry('manipulatif', 'Manipülatif', 'İnsanları fark ettirmeden yönlendirir.'),
      entry('sadik-trait', 'Sadık', 'Klanına ya da yakınlarına bağlı kalır.'),
      entry('acla-bogusan', 'Açlıkla Boğuşan', 'Kan açlığını bastırmakta zorlanır.'),
    ],
    perks: [
      entry('hipnoz', 'Hipnoz', 'İnsanları bakışlarıyla etkisi altına alır.'),
      entry('golgelerle-kaynasma', 'Gölgelerle Kaynaşma', 'Karanlıkta neredeyse görünmez olur.'),
      entry('ustun-guc', 'Üstün Güç', 'İnsan üstü fiziksel kuvvete sahiptir.'),
      entry('kan-buyusu', 'Kan Büyüsü', 'Kanı kullanarak büyüsel etkiler yaratır.'),
      entry('hizli-iyilesme', 'Hızlı İyileşme', 'Yaraları olağanüstü hızlı iyileşir.'),
    ],
    items: [
      entry('kan-sisesi', 'Kan Şişesi', 'Acil durumlar için saklanmış kan.'),
      entry('antika-yuzuk', 'Antika Yüzük', 'Yüzyıllar öncesinden kalma bir yüzük.'),
      entry('gizli-mezar-anahtari', 'Gizli Mezar Anahtarı', 'Güvenli bir sığınağın anahtarı.'),
      entry('kadim-ahit-belgesi', 'Kadim Ahit Belgesi', 'Eski bir anlaşmayı kanıtlayan belge.'),
      entry('gumus-bicak', 'Gümüş Bıçak', 'Tehlikeli ama gerektiğinde işe yarayan bir silah.'),
    ],
  },
  {
    id: 'builtin-cosmic-horror',
    label: '⭐ Kozmik Dehşet Tarzı',
    name: 'Kozmik Dehşet',
    theme: 'cosmic-horror',
    stats: [
      stat('guc', 'Güç', 'Fiziksel kuvvet'),
      stat('beceri', 'Beceri', 'El becerisi, çeviklik, hassasiyet'),
      stat('zeka', 'Zeka', 'Analiz, araştırma, bilgi'),
      stat('akil-sagligi', 'Akıl Sağlığı', 'Dehşete ve bilinmeyene karşı direnç'),
      stat('sans', 'Şans', 'Beklenmedik anlarda iyi ya da kötü talih'),
    ],
    resources: [resource('can', 'Can Puanı', 10)],
    races: [],
    classes: [
      entry('akademisyen', 'Akademisyen', 'Kadim bilgiye meraklı araştırmacı.'),
      entry('dedektif', 'Dedektif', 'Gerçeği ortaya çıkarmakta ısrarcı.'),
      entry('gazeteci', 'Gazeteci', 'Hikayenin peşini asla bırakmaz.'),
      entry('doktor', 'Doktor', 'Bedeni ve zihni bir arada tutmaya çalışır.'),
      entry('denizci', 'Denizci', 'Denizin ve derinliklerin garipliklerine aşina.'),
      entry('tarikat-kacagi', 'Tarikat Kaçağı', 'Karanlık bir tarikattan kaçmış biri.'),
    ],
    subclasses: [],
    traits: [
      entry('merakli', 'Meraklı', 'Bilinmeyeni araştırmaktan kendini alamaz.'),
      entry('supheci', 'Şüpheci', 'Kolay kolay ikna olmaz.'),
      entry('paranoyak', 'Paranoyak', 'Sürekli tetikte, kimseye tam güvenmez.'),
      entry('inatci', 'İnatçı', 'Peşini bıraktığı çok az şey vardır.'),
      entry('kirilgan', 'Kırılgan', 'Dehşet karşısında kolay sarsılır.'),
    ],
    perks: [
      entry('arastirma-ustaligi', 'Araştırma Ustalığı', 'Kütüphane ve arşivlerde hızlı sonuç bulur.'),
      entry('silah-egitimi', 'Silah Eğitimi', 'Ateşli silahları güvenle kullanır.'),
      entry('ilk-yardim', 'İlk Yardım', 'Yaraları sahada tedavi edebilir.'),
      entry('eski-dilleri-okuma', 'Eski Dilleri Okuma', 'Unutulmuş dilleri ve yazıları çözebilir.'),
      entry('sogukkanlilik-perk', 'Soğukkanlılık', 'Dehşet anında daha az sarsılır.'),
    ],
    items: [
      entry('el-fenerin', 'El Feneri', 'Karanlık yerlerde en sadık yoldaş.'),
      entry('gunluk', 'Günlük', 'İçinde tuhaf notlar olan bir defter.'),
      entry('silah', 'Silah', 'Basit ama güvenilir bir savunma aracı.'),
      entry('ilac-kutusu', 'İlaç Kutusu', 'Temel yaralanmalar için malzeme.'),
      entry('tuhaf-obje', 'Tuhaf Bir Obje', 'Ne olduğu tam olarak anlaşılamayan bir eşya.'),
    ],
  },
  {
    id: 'builtin-western',
    label: '⭐ Vahşi Batı Tarzı',
    name: 'Vahşi Batı',
    theme: 'western',
    stats: [
      stat('nisancilik', 'Nişancılık', 'Ateşli silahlarla isabet'),
      stat('ceviklik', 'Çeviklik', 'Hız, refleks, at biniciliği'),
      stat('dayaniklilik', 'Dayanıklılık', 'Yaraya, susuzluğa, yorgunluğa direnç'),
      stat('karizma', 'Karizma', 'İkna, blöf, liderlik'),
      stat('kurnazlik', 'Kurnazlık', 'Hile, gözlem, strateji'),
    ],
    resources: [resource('can', 'Can Puanı', 10)],
    races: [],
    classes: [
      entry('serif', 'Şerif', 'Kasabanın kanununu koruyan otorite.'),
      entry('silahsor', 'Silahşör', 'Silahıyla ün salmış yalnız kurt.'),
      entry('kumarbaz', 'Kumarbaz', 'Masada da sokakta da hep bir adım önde.'),
      entry('ciftci', 'Çiftçi', 'Toprağını korumaya kararlı sıradan biri.'),
      entry('odul-avcisi', 'Ödül Avcısı', 'Para karşılığı kanun kaçaklarını kovalar.'),
      entry('dedektif', 'Dedektif', 'İzleri takip etmekte usta.'),
    ],
    subclasses: [],
    traits: [
      entry('cesur', 'Cesur', 'Tehlikeden kaçmaz.'),
      entry('sessiz', 'Sessiz', 'Az konuşur, çok gözlemler.'),
      entry('namuslu', 'Namuslu', 'Verdiği sözü tutar.'),
      entry('kanun-kacagi', 'Kanun Kaçağı', 'Geçmişinde gizlenecek bir şeyler var.'),
      entry('sadik', 'Sadık', 'Yanındakileri korur.'),
    ],
    perks: [
      entry('hizli-cekis', 'Hızlı Çekiş', 'Silahını herkesten önce çeker.'),
      entry('at-biniciligi', 'At Biniciliği', 'At üzerinde olağanüstü hakimiyeti var.'),
      entry('kement-ustaligi', 'Kement Ustalığı', 'Kementle hedefi asla kaçırmaz.'),
      entry('ikna-kabiliyeti', 'İkna Kabiliyeti', 'Sözleriyle insanları kolayca yönlendirir.'),
      entry('keskin-nisanci', 'Keskin Nişancı', 'Uzun menzilden bile isabetli vurur.'),
    ],
    items: [
      entry('revolver', 'Revolver', 'Güvenilir, altı mermilik bir silah.'),
      entry('winchester', 'Winchester Tüfek', 'Uzun menzilli, güçlü bir tüfek.'),
      entry('deri-eyer', 'Deri Eyer', 'Uzun yolculuklar için dayanıklı bir eyer.'),
      entry('kement', 'Kement', 'Hem avda hem çatışmada işe yarar.'),
      entry('viski-sisesi', 'Viski Şişesi', 'Zor bir günün ardından teselli.'),
    ],
  },
];
