export const THEMES = [
  {
    id: 'post-apocalyptic',
    name: 'Post-Apokaliptik',
    vars: {
      '--bg': '#120d09',
      '--bg-panel': '#1c150e',
      '--bg-panel-alt': '#241a10',
      '--border': '#3c2c18',
      '--amber': '#cf9a3f',
      '--amber-light': '#e8bd6d',
      '--amber-dim': '#8a662f',
      '--text': '#ece2d0',
      '--text-muted': '#b0a086',
      '--danger': '#a5433a',
      '--ok': '#6b8f5c',
      '--tired': '#8a7a3f',
      '--font-heading': "'Cinzel', serif",
      '--radius': '10px',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    vars: {
      '--bg': '#07050d',
      '--bg-panel': '#0f0b1d',
      '--bg-panel-alt': '#171029',
      '--border': '#3a2a5c',
      '--amber': '#ff2fd4',
      '--amber-light': '#7df9ff',
      '--amber-dim': '#a3129e',
      '--text': '#e7e9ff',
      '--text-muted': '#8d87b5',
      '--danger': '#ff3860',
      '--ok': '#39ff9d',
      '--tired': '#ffd23f',
      '--font-heading': "'Orbitron', sans-serif",
      '--radius': '3px',
    },
  },
  {
    id: 'high-fantasy',
    name: 'Yüksek Fantazi',
    vars: {
      '--bg': '#160f24',
      '--bg-panel': '#20172f',
      '--bg-panel-alt': '#2a1f3b',
      '--border': '#4a3768',
      '--amber': '#d4af37',
      '--amber-light': '#f3d878',
      '--amber-dim': '#9c7f24',
      '--text': '#efe6ff',
      '--text-muted': '#b0a3cc',
      '--danger': '#c0455e',
      '--ok': '#6fae7a',
      '--tired': '#c99a4b',
      '--font-heading': "'Cinzel Decorative', serif",
      '--radius': '14px',
    },
  },
  {
    id: 'gothic-horror',
    name: 'Gotik Korku',
    vars: {
      '--bg': '#0a0505',
      '--bg-panel': '#150a0a',
      '--bg-panel-alt': '#1e0e0e',
      '--border': '#3f1414',
      '--amber': '#8f1d1d',
      '--amber-light': '#c94c4c',
      '--amber-dim': '#5c1010',
      '--text': '#e6d8d8',
      '--text-muted': '#a08787',
      '--danger': '#e34747',
      '--ok': '#5c8f6e',
      '--tired': '#8f6a3f',
      '--font-heading': "'UnifrakturMaguntia', cursive",
      '--radius': '4px',
    },
  },
  {
    id: 'sci-fi',
    name: 'Bilim Kurgu',
    vars: {
      '--bg': '#040810',
      '--bg-panel': '#0a1220',
      '--bg-panel-alt': '#101c30',
      '--border': '#1f3a5c',
      '--amber': '#3fd0ff',
      '--amber-light': '#a6ecff',
      '--amber-dim': '#1c86ad',
      '--text': '#e3f3ff',
      '--text-muted': '#7fa2c2',
      '--danger': '#ff5f5f',
      '--ok': '#4be6a0',
      '--tired': '#ffcf5c',
      '--font-heading': "'Rajdhani', sans-serif",
      '--radius': '6px',
    },
  },
  {
    id: 'western',
    name: 'Vahşi Batı',
    vars: {
      '--bg': '#1a120a',
      '--bg-panel': '#241a0f',
      '--bg-panel-alt': '#2e2013',
      '--border': '#4a3620',
      '--amber': '#c17f3f',
      '--amber-light': '#e0a868',
      '--amber-dim': '#8a5a2a',
      '--text': '#ecdcc0',
      '--text-muted': '#a89372',
      '--danger': '#a5433a',
      '--ok': '#7a8f5c',
      '--tired': '#b08a3f',
      '--font-heading': "'Rye', serif",
      '--radius': '4px',
    },
  },
  {
    id: 'steampunk',
    name: 'Steampunk',
    vars: {
      '--bg': '#100d08',
      '--bg-panel': '#1a140d',
      '--bg-panel-alt': '#241b11',
      '--border': '#4a3a1f',
      '--amber': '#b87333',
      '--amber-light': '#d99a4e',
      '--amber-dim': '#7a4d1f',
      '--text': '#e8dcc4',
      '--text-muted': '#a8977a',
      '--danger': '#a5433a',
      '--ok': '#6a8f6b',
      '--tired': '#8f7a3f',
      '--font-heading': "'Special Elite', monospace",
      '--radius': '3px',
    },
  },
  {
    id: 'pirate',
    name: 'Korsan',
    vars: {
      '--bg': '#071214',
      '--bg-panel': '#0d1c1f',
      '--bg-panel-alt': '#13262a',
      '--border': '#234348',
      '--amber': '#d4af37',
      '--amber-light': '#f0d878',
      '--amber-dim': '#8f7a24',
      '--text': '#dfeef0',
      '--text-muted': '#82a3a8',
      '--danger': '#c0453f',
      '--ok': '#4b9e7a',
      '--tired': '#c99a4b',
      '--font-heading': "'Pirata One', cursive",
      '--radius': '6px',
    },
  },
  {
    id: 'mythology',
    name: 'Antik Mitoloji',
    vars: {
      '--bg': '#14110c',
      '--bg-panel': '#1e1a12',
      '--bg-panel-alt': '#282218',
      '--border': '#4a4128',
      '--amber': '#d4af37',
      '--amber-light': '#f3d878',
      '--amber-dim': '#9c7f24',
      '--text': '#f0e9d8',
      '--text-muted': '#b5a988',
      '--danger': '#a5433a',
      '--ok': '#6b8f6a',
      '--tired': '#b08a3f',
      '--font-heading': "'Almendra SC', serif",
      '--radius': '8px',
    },
  },
  {
    id: 'noir',
    name: 'Film Noir',
    vars: {
      '--bg': '#0a0a0a',
      '--bg-panel': '#141414',
      '--bg-panel-alt': '#1e1e1e',
      '--border': '#3a3a3a',
      '--amber': '#c0392b',
      '--amber-light': '#e05a4a',
      '--amber-dim': '#7a251c',
      '--text': '#e8e8e8',
      '--text-muted': '#999999',
      '--danger': '#e0473a',
      '--ok': '#6a8f6a',
      '--tired': '#999999',
      '--font-heading': "'Oswald', sans-serif",
      '--radius': '2px',
    },
  },
  {
    id: 'wuxia',
    name: 'Doğu Fantazisi',
    vars: {
      '--bg': '#0c1410',
      '--bg-panel': '#131f19',
      '--bg-panel-alt': '#1a2b22',
      '--border': '#2e4a3a',
      '--amber': '#3fae74',
      '--amber-light': '#6fd9a0',
      '--amber-dim': '#256b48',
      '--text': '#e6f2ea',
      '--text-muted': '#8bab99',
      '--danger': '#c9433f',
      '--ok': '#4bae7a',
      '--tired': '#c9a13f',
      '--font-heading': "'Ma Shan Zheng', cursive",
      '--radius': '10px',
    },
  },
  {
    id: 'space-opera',
    name: 'Uzay Operası',
    vars: {
      '--bg': '#0c0818',
      '--bg-panel': '#150f24',
      '--bg-panel-alt': '#1e1730',
      '--border': '#3a2a5c',
      '--amber': '#d63fd6',
      '--amber-light': '#ff8ce0',
      '--amber-dim': '#8a1f8a',
      '--text': '#f0e6ff',
      '--text-muted': '#a691c2',
      '--danger': '#ff4f6b',
      '--ok': '#4be6a0',
      '--tired': '#ffcf5c',
      '--font-heading': "'Audiowide', sans-serif",
      '--radius': '8px',
    },
  },
  {
    id: 'zombie',
    name: 'Zombi Kıyameti',
    vars: {
      '--bg': '#0d0f0a',
      '--bg-panel': '#14170f',
      '--bg-panel-alt': '#1b1f14',
      '--border': '#333a26',
      '--amber': '#7a8f3f',
      '--amber-light': '#a3c25c',
      '--amber-dim': '#4f5c26',
      '--text': '#dbe0c8',
      '--text-muted': '#8f9678',
      '--danger': '#a51d1d',
      '--ok': '#5c8f5c',
      '--tired': '#8a7a3f',
      '--font-heading': "'Nosifer', cursive",
      '--radius': '3px',
    },
  },
  {
    id: 'vampire',
    name: 'Vampir Aristokrasisi',
    vars: {
      '--bg': '#0a0509',
      '--bg-panel': '#150a12',
      '--bg-panel-alt': '#1f0e1a',
      '--border': '#3f1a35',
      '--amber': '#8f1d4f',
      '--amber-light': '#c94c7f',
      '--amber-dim': '#5c1033',
      '--text': '#e6d8e0',
      '--text-muted': '#a0879a',
      '--danger': '#e0334f',
      '--ok': '#5c8f6e',
      '--tired': '#8f6a3f',
      '--font-heading': "'Cinzel Decorative', serif",
      '--radius': '6px',
    },
  },
  {
    id: 'viking',
    name: 'Viking',
    vars: {
      '--bg': '#0a0e12',
      '--bg-panel': '#10161c',
      '--bg-panel-alt': '#161e26',
      '--border': '#2c3c4a',
      '--amber': '#6fa8c9',
      '--amber-light': '#9fcbe6',
      '--amber-dim': '#3f6a85',
      '--text': '#dbe8f0',
      '--text-muted': '#8199a8',
      '--danger': '#a5433a',
      '--ok': '#5c8f7a',
      '--tired': '#a89a6a',
      '--font-heading': "'Uncial Antiqua', cursive",
      '--radius': '4px',
    },
  },
  {
    id: 'arabian',
    name: 'Çöl Masalları',
    vars: {
      '--bg': '#150f08',
      '--bg-panel': '#1f160d',
      '--bg-panel-alt': '#291d12',
      '--border': '#4a3620',
      '--amber': '#d4af37',
      '--amber-light': '#f3d878',
      '--amber-dim': '#9c7f24',
      '--text': '#f0e4c8',
      '--text-muted': '#b5a37a',
      '--danger': '#c0453f',
      '--ok': '#3fae9e',
      '--tired': '#c99a4b',
      '--font-heading': "'Scheherazade New', serif",
      '--radius': '12px',
    },
  },
  {
    id: 'cosmic-horror',
    name: 'Kozmik Dehşet',
    vars: {
      '--bg': '#0a0c0a',
      '--bg-panel': '#10140f',
      '--bg-panel-alt': '#161c14',
      '--border': '#2c3a2a',
      '--amber': '#7a3fae',
      '--amber-light': '#a877d9',
      '--amber-dim': '#4f2670',
      '--text': '#d8e0d0',
      '--text-muted': '#8fa085',
      '--danger': '#a51d5c',
      '--ok': '#3f8f6a',
      '--tired': '#6a8f3f',
      '--font-heading': "'Metal Mania', cursive",
      '--radius': '2px',
    },
  },
  {
    id: 'superhero',
    name: 'Süper Kahraman',
    vars: {
      '--bg': '#0a0e1a',
      '--bg-panel': '#121a2e',
      '--bg-panel-alt': '#1a253f',
      '--border': '#2c4a7a',
      '--amber': '#e63946',
      '--amber-light': '#ff6b78',
      '--amber-dim': '#a5232f',
      '--text': '#f0f4ff',
      '--text-muted': '#8fa3c2',
      '--danger': '#e63946',
      '--ok': '#4be678',
      '--tired': '#ffd23f',
      '--font-heading': "'Bangers', cursive",
      '--radius': '6px',
    },
  },
  {
    id: 'heist',
    name: 'Soygun',
    vars: {
      '--bg': '#0a0a0a',
      '--bg-panel': '#141414',
      '--bg-panel-alt': '#1c1c1c',
      '--border': '#3a3226',
      '--amber': '#d4af37',
      '--amber-light': '#f0d878',
      '--amber-dim': '#8f7a24',
      '--text': '#e8e4d8',
      '--text-muted': '#999080',
      '--danger': '#a5433a',
      '--ok': '#4b8f6a',
      '--tired': '#8a7a3f',
      '--font-heading': "'Bebas Neue', sans-serif",
      '--radius': '2px',
    },
  },
  {
    id: 'kaiju',
    name: 'Kaiju',
    vars: {
      '--bg': '#0f0a08',
      '--bg-panel': '#191210',
      '--bg-panel-alt': '#231a16',
      '--border': '#4a3020',
      '--amber': '#e8622e',
      '--amber-light': '#ff8f5c',
      '--amber-dim': '#a5401a',
      '--text': '#ecdfd4',
      '--text-muted': '#a8927e',
      '--danger': '#d4291f',
      '--ok': '#6a8f5c',
      '--tired': '#c9a13f',
      '--font-heading': "'Bungee', cursive",
      '--radius': '4px',
    },
  },
  {
    id: 'carnival',
    name: 'Karanlık Karnaval',
    vars: {
      '--bg': '#0d0508',
      '--bg-panel': '#170a0f',
      '--bg-panel-alt': '#211016',
      '--border': '#4a1f2c',
      '--amber': '#d4af37',
      '--amber-light': '#f3d878',
      '--amber-dim': '#9c7f24',
      '--text': '#f0dfe0',
      '--text-muted': '#a8828f',
      '--danger': '#c0182e',
      '--ok': '#4b8f6a',
      '--tired': '#a13f6a',
      '--font-heading': "'Eater', cursive",
      '--radius': '10px',
    },
  },
];

export const DEFAULT_THEME_ID = 'post-apocalyptic';

export function getTheme(id) {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}

export function applyTheme(id) {
  const theme = getTheme(id);
  Object.entries(theme.vars).forEach(([key, value]) => {
    document.documentElement.style.setProperty(key, value);
  });
}
